---
- name: Set timezone
  timezone:
    name: Europe/London

- name: set hostname
  lineinfile:
    dest: /etc/hostname
    line: "{{ ansible_host }}"
    insertbefore: BOF
    #problem here ****

- name: install ntp
  apt: 
    name: "{{ items }}"
    state: present
    with_items:
      - ntp
      - ntpdate
    update_cache: yes

- name: configure ntp settings
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    notify:
      - restart ntp

- name: set firewall rules
  blockinfile:
    dest: /etc/rc.local
    block: |
      # rules for NTP update
      iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
      iptables -A INPUT -p udp --sport 123 -j ACCEPT
    insertbefore: "exit 0"

- name: retrieve rc.local settings
  shell: ". /etc/rc.local"

- name: stop ntp service
  service:
    name: ntpd
    state: stopped

- name: set time
  command: ntpdate {{ alias.ntp }}

- name: start ntp service
  service:
    name: ntpd
    state: started

- name: disable challenge response for ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'

- name: disable password authentication for ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: ensure PAM is enabled 
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^UsePAM'
    line: 'UsePAM yes'
  notify:
    - restart ssh
