---
- name: install dhcp
  apt:
    name: isc-dhcp-server
    state: present

- name: configure dhcp
  template:
    src: dhcp.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify:
    - restart dhcp

- name: start dhcp service
  service:
    name: isc-dhcp-server
    state: started
    enabled: true
