---
- name: deploy ssh key
  copy:
    src: "{{ item }}"
    dest: /home/pi/.ssh/
    owner: pi
    group: pi
    mode: 0600
  with_fileglob:
    - ".ssh/*"

- name: set hostname
  lineinfile:
    dest: /etc/hostname
    line: "{{ ansible_host }}"
    insertbefore: BOF
    #problem because it needs to replace the entry!!!

- name: install mosh
  apt:
    name: mosh
    state: present
    update_cache: yes

- name: update firewall for mosh
  blockinfile:
    dest: /etc/rc.local
    block: |
      # rules for mosh
      iptables -I INPUT 1 -p udp --dport 60000:61000 -j ACCEPT
    insertbefore: "exit 0"

- name: apply settings from rc.local
  shell: ". /etc/rc.local"
