---
- name: Install Bind9
  apt: 
    name: "{{ item }}"
    state: present 
  with_items:
    - bind9
    - bind9-doc

- name: update options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
    backup: yes
    force: yes
  notify:
    - restart bind9

- name: create zones directory
  file:
    path: /etc/bind/zones
    state: directory

- name: configure local DNS zone
  template:
    src: db.home.j2
    dest: /etc/bind/zones/db.home
    owner: root
    group: bind
    mode: 0644
    force: yes

- name: configure reverse DNS zone
  copy:
    src: db.192
    dest: /etc/bind/zones/db.192
    owner: root
    group: bind
    mode: 0644
    force: yes
  notify:
    - restart bind9

- name: deploy adblocking files
  copy:
    src: dummy-block
    dest: /etc/bind/zones/dummy-block
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes

- name: set static IP address
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes

- name: reboot to enforce interface configuration
  shell: sleep 2 && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for server to come back online
  local_action: 
    module: wait_for
        host="{{ ansible_default_ipv4.address }}"
        port=22
        delay=30
        timeout=300
        connect_timeout=15
