---
- name: Install Bind9
  apt: name={{ item }} state=present
  with_items:
    - bind9
    - bind9-doc
  update_cache: yes

- name: update options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
    backup: yes
    force: yes
  notify:
    - restart bind9

- name: configure local DNS zone
  template:
    src: db.home.j2
    dest: /etc/bind/zones/db.home
    owner: root
    group: bind
    mode: 0644
    force: yes

- name: configure reverse DNS zone
  copy:
    src: db.192
    dest: /etc/bind/zones/db.192
    owner: root
    group: bind
    mode: 0644
    force: yes
  notify:
    - restart bind9

- name: set static IP address
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes

- name: reboot to enforce interface configuration
  command: reboot
  async: 0
  poll: 0

- name: wait for server to come back online
  local_action: 
    - wait_for:
        host: {{ ansible_ssh_host | default(inventory_hostname) }}
        state: started
        port: 22
        delay: 30
        timeout: 300
        connect_timeout: 15
