---
- name: install ntp
  apt: 
    name: ntp
    state: present
    update_cache: yes

- name: update ntp.conf
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  notify:
    - restart ntp

- name: set firewall rules
  blockinfile:
    path: /etc/rc.local
    block: |
      iptables -A INPUT -p udp --dport 123 -j ACCEPT
      iptables -A OUTPUT -p udp --sport 123 -j ACCEPT
    insertbefore: "exit 0"

- name: call new rc.local file
  command: "source /etc/rc.local"

- name: start ntp service
  service: 
    name: ntpd
    state: started
    enabled: true
